# Generated by Django 5.1.4 on 2025-01-15 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0002_subjectcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsubject',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='backend_api.subjectcategory'),
            preserve_default=False,
        ),
    ]
